### ISSUE TITLE
Better calibration options

### ISSUE THREAD

**Issue by Econtilde** [7thbeatgames/adofai#10]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

The current calibration minigame can be a bit too slow/short to be reliable for fast levels

### Suggestion / Solution

Add a double speed version of the calibration minigame to allow for twice the amount of inputs and hopefully lead to a more accurate offset. Additionally, another feature that could help solve the problem is adding a calibration play mode similar to NotITG's where you play through any level you want and the game automatically sets your offset to the average offset of your inputs during play

**Comment by Patashu** [comment]
+1 for 'suggest offset based on your median input after finishing a level' (I think median is better than mean since it's not skewed by outliers, but I guess you can't have very large outliers in ADOFAI so they might end up similar anyway) and +1 for 'double speed/arbitrarily long calibration minigame
